import { describe, it, expect } from 'vitest';
import { issueDeviceCert, verifyDeviceCert, _internals } from './device-cert.js';

// Cross-language vector generated by proxion_messenger_core.device_cert
// (issue_device_cert) with fixed seeds and now=1700000000. Because Ed25519 is
// deterministic, a byte-identical canonical format yields a byte-identical
// signature — so matching this proves JS<->Python cert compatibility.
const VEC = {
    account_seed_hex: '000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f',
    account_pub_b64u: 'A6EHv_POEL4dcN0Y50vAmWfk1jCbpQ1fHdyGZBJVMbg',
    device_did: 'did:key:z6MkhFwXNFWosLeugvSf4wcL9t3uuRXueGSFTRgSvHhWj5G2',
    account_did: 'did:key:z6MkehRgf7yJbgaGfYsdoAsKdBPE3dj2CYhowQdcjqSJgvVd',
    issued_at: 1700000000,
    expires_at: 1731536000,
    canonical_hex: '00386469643a6b65793a7a364d6b656852676637794a62676147665973646f41734b6442504533646a324359686f775164636a71534a677656647c00386469643a6b65793a7a364d6b684677584e46576f734c6575677653663477634c39743375755258756547534654526753764868576a3547327c000a313730303030303030307c000a31373331353336303030',
    signature_b64: '6J/glmkMBBHactIlO2Ed0gUrO6dZnbarprT8AxfNuIQ8JOb2f+bf35LkK/vu0Hjib4QXecrpBCNBW9xQXZ/BDg==',
};

function hexToBytes(hex) {
    const u = new Uint8Array(hex.length / 2);
    for (let i = 0; i < u.length; i++) u[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
    return u;
}
function bytesToHex(u) {
    return [...u].map(b => b.toString(16).padStart(2, '0')).join('');
}
function b64url(bytes) {
    let s = ''; for (const b of bytes) s += String.fromCharCode(b);
    return btoa(s).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

async function importAccountKey() {
    const seed = hexToBytes(VEC.account_seed_hex);
    const jwk = {
        kty: 'OKP', crv: 'Ed25519',
        d: b64url(seed), x: VEC.account_pub_b64u,
        key_ops: ['sign'], ext: true,
    };
    return crypto.subtle.importKey('jwk', jwk, { name: 'Ed25519' }, false, ['sign']);
}

function vectorCert() {
    return {
        '@type': 'ProxionDeviceCert', version: 1,
        account_did: VEC.account_did, device_did: VEC.device_did,
        issued_at: VEC.issued_at, expires_at: VEC.expires_at,
        signature: VEC.signature_b64,
    };
}

describe('device-cert canonical format', () => {
    it('produces byte-identical canonical bytes to Python', () => {
        const canon = _internals._canonical(VEC.account_did, VEC.device_did, VEC.issued_at, VEC.expires_at);
        expect(bytesToHex(canon)).toBe(VEC.canonical_hex);
    });
});

describe('issueDeviceCert cross-language equivalence', () => {
    it('signs identically to Python (deterministic Ed25519)', async () => {
        const key = await importAccountKey();
        const cert = await issueDeviceCert(key, VEC.account_did, VEC.device_did, {
            ttlDays: 365, now: VEC.issued_at,
        });
        expect(cert.expires_at).toBe(VEC.expires_at);
        expect(cert.signature).toBe(VEC.signature_b64);
    });
});

describe('verifyDeviceCert', () => {
    it('accepts a Python-issued cert before expiry', async () => {
        const got = await verifyDeviceCert(vectorCert(), {
            expectedDeviceDid: VEC.device_did, now: VEC.issued_at + 3600,
        });
        expect(got).toBe(VEC.account_did);
    });

    it('rejects when device_did does not match the expectation', async () => {
        const got = await verifyDeviceCert(vectorCert(), {
            expectedDeviceDid: 'did:key:z6MkOtherDeviceDidHerePlaceholderXXXXXXXXXXX',
            now: VEC.issued_at + 3600,
        });
        expect(got).toBeNull();
    });

    it('rejects an expired cert', async () => {
        const got = await verifyDeviceCert(vectorCert(), { now: VEC.expires_at + 1 });
        expect(got).toBeNull();
    });

    it('rejects a tampered signature', async () => {
        const bad = vectorCert();
        bad.signature = btoa(String.fromCharCode(...new Uint8Array(64)));
        expect(await verifyDeviceCert(bad, { now: VEC.issued_at + 3600 })).toBeNull();
    });

    it('rejects a tampered signed field', async () => {
        const bad = vectorCert();
        bad.device_did = VEC.account_did; // swap in a different device
        expect(await verifyDeviceCert(bad, { now: VEC.issued_at + 3600 })).toBeNull();
    });

    it('round-trips a freshly issued cert', async () => {
        const key = await importAccountKey();
        const cert = await issueDeviceCert(key, VEC.account_did, VEC.device_did, { ttlDays: 30 });
        const got = await verifyDeviceCert(cert, { expectedDeviceDid: VEC.device_did });
        expect(got).toBe(VEC.account_did);
    });
});
